services:
  listenbrainz-wrapped:
    image: ghcr.io/iostpa/listenbrainz-wrapped:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file: ".env"